# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quentin/Desktop/GitProjects/VM/sdvu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quentin/Desktop/GitProjects/VM/sdvu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quentin/Desktop/GitProjects/VM/sdvu/CMakeFiles /home/quentin/Desktop/GitProjects/VM/sdvu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quentin/Desktop/GitProjects/VM/sdvu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdvu

# Build rule for target.
sdvu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdvu
.PHONY : sdvu

# fast build rule for target.
sdvu/fast:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/build
.PHONY : sdvu/fast

src/chunk.o: src/chunk.c.o

.PHONY : src/chunk.o

# target to build an object file
src/chunk.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/chunk.c.o
.PHONY : src/chunk.c.o

src/chunk.i: src/chunk.c.i

.PHONY : src/chunk.i

# target to preprocess a source file
src/chunk.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/chunk.c.i
.PHONY : src/chunk.c.i

src/chunk.s: src/chunk.c.s

.PHONY : src/chunk.s

# target to generate assembly for a file
src/chunk.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/chunk.c.s
.PHONY : src/chunk.c.s

src/compiler.o: src/compiler.c.o

.PHONY : src/compiler.o

# target to build an object file
src/compiler.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/compiler.c.o
.PHONY : src/compiler.c.o

src/compiler.i: src/compiler.c.i

.PHONY : src/compiler.i

# target to preprocess a source file
src/compiler.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/compiler.c.i
.PHONY : src/compiler.c.i

src/compiler.s: src/compiler.c.s

.PHONY : src/compiler.s

# target to generate assembly for a file
src/compiler.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/compiler.c.s
.PHONY : src/compiler.c.s

src/disassembler.o: src/disassembler.c.o

.PHONY : src/disassembler.o

# target to build an object file
src/disassembler.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/disassembler.c.o
.PHONY : src/disassembler.c.o

src/disassembler.i: src/disassembler.c.i

.PHONY : src/disassembler.i

# target to preprocess a source file
src/disassembler.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/disassembler.c.i
.PHONY : src/disassembler.c.i

src/disassembler.s: src/disassembler.c.s

.PHONY : src/disassembler.s

# target to generate assembly for a file
src/disassembler.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/disassembler.c.s
.PHONY : src/disassembler.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/main.c.s
.PHONY : src/main.c.s

src/mmemory.o: src/mmemory.c.o

.PHONY : src/mmemory.o

# target to build an object file
src/mmemory.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/mmemory.c.o
.PHONY : src/mmemory.c.o

src/mmemory.i: src/mmemory.c.i

.PHONY : src/mmemory.i

# target to preprocess a source file
src/mmemory.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/mmemory.c.i
.PHONY : src/mmemory.c.i

src/mmemory.s: src/mmemory.c.s

.PHONY : src/mmemory.s

# target to generate assembly for a file
src/mmemory.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/mmemory.c.s
.PHONY : src/mmemory.c.s

src/register.o: src/register.c.o

.PHONY : src/register.o

# target to build an object file
src/register.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/register.c.o
.PHONY : src/register.c.o

src/register.i: src/register.c.i

.PHONY : src/register.i

# target to preprocess a source file
src/register.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/register.c.i
.PHONY : src/register.c.i

src/register.s: src/register.c.s

.PHONY : src/register.s

# target to generate assembly for a file
src/register.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/register.c.s
.PHONY : src/register.c.s

src/scanner.o: src/scanner.c.o

.PHONY : src/scanner.o

# target to build an object file
src/scanner.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/scanner.c.o
.PHONY : src/scanner.c.o

src/scanner.i: src/scanner.c.i

.PHONY : src/scanner.i

# target to preprocess a source file
src/scanner.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/scanner.c.i
.PHONY : src/scanner.c.i

src/scanner.s: src/scanner.c.s

.PHONY : src/scanner.s

# target to generate assembly for a file
src/scanner.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/scanner.c.s
.PHONY : src/scanner.c.s

src/sstring.o: src/sstring.c.o

.PHONY : src/sstring.o

# target to build an object file
src/sstring.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/sstring.c.o
.PHONY : src/sstring.c.o

src/sstring.i: src/sstring.c.i

.PHONY : src/sstring.i

# target to preprocess a source file
src/sstring.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/sstring.c.i
.PHONY : src/sstring.c.i

src/sstring.s: src/sstring.c.s

.PHONY : src/sstring.s

# target to generate assembly for a file
src/sstring.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/sstring.c.s
.PHONY : src/sstring.c.s

src/table.o: src/table.c.o

.PHONY : src/table.o

# target to build an object file
src/table.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/table.c.o
.PHONY : src/table.c.o

src/table.i: src/table.c.i

.PHONY : src/table.i

# target to preprocess a source file
src/table.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/table.c.i
.PHONY : src/table.c.i

src/table.s: src/table.c.s

.PHONY : src/table.s

# target to generate assembly for a file
src/table.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/table.c.s
.PHONY : src/table.c.s

src/value.o: src/value.c.o

.PHONY : src/value.o

# target to build an object file
src/value.c.o:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/value.c.o
.PHONY : src/value.c.o

src/value.i: src/value.c.i

.PHONY : src/value.i

# target to preprocess a source file
src/value.c.i:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/value.c.i
.PHONY : src/value.c.i

src/value.s: src/value.c.s

.PHONY : src/value.s

# target to generate assembly for a file
src/value.c.s:
	$(MAKE) -f CMakeFiles/sdvu.dir/build.make CMakeFiles/sdvu.dir/src/value.c.s
.PHONY : src/value.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sdvu"
	@echo "... src/chunk.o"
	@echo "... src/chunk.i"
	@echo "... src/chunk.s"
	@echo "... src/compiler.o"
	@echo "... src/compiler.i"
	@echo "... src/compiler.s"
	@echo "... src/disassembler.o"
	@echo "... src/disassembler.i"
	@echo "... src/disassembler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mmemory.o"
	@echo "... src/mmemory.i"
	@echo "... src/mmemory.s"
	@echo "... src/register.o"
	@echo "... src/register.i"
	@echo "... src/register.s"
	@echo "... src/scanner.o"
	@echo "... src/scanner.i"
	@echo "... src/scanner.s"
	@echo "... src/sstring.o"
	@echo "... src/sstring.i"
	@echo "... src/sstring.s"
	@echo "... src/table.o"
	@echo "... src/table.i"
	@echo "... src/table.s"
	@echo "... src/value.o"
	@echo "... src/value.i"
	@echo "... src/value.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

